version: '3'
services:

  drom-emulation:
    build: ./widget
    ports:
      - "3001:80"
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096

  front:
    build: ./front
    ports:
      - "3000:80"
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096

    depends_on:
      - back

  back:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: back
      dockerfile: ./Dockerfile
    container_name: back
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db1:5432/bigdata
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    ports:
      - "8081:8081"
    depends_on:
      - db1

  db1:
    image: postgres:14-alpine
    container_name: db1
    restart: always

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bigdata

    #command: --init-file /resources/schema.sql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: