version: '3'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: back
      dockerfile: ./Dockerfile
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bigdata
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    build:
      context: back
      dockerfile: ../back/Dockerfile.development

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bigdata

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: