version: '3'
services:

  drom-emulation:
    build: ./widget
    ports:
      - "3001:80"
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096

  front:
    build: ./front
    ports:
      - "3000:80"
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096

    depends_on:
      - back

  back:
    env_file:
      - .env
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: back
      dockerfile: ./Dockerfile
    container_name: back
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8081:8081"
    network_mode: host
    depends_on:
      - db1

  db1:
    env_file:
      - .env
    image: postgres:13-alpine
    container_name: db1
    restart: always

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}

    #command: --init-file /resources/schema.sql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: