server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bigdata
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
  mail:
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.yandex.ru
    host: smtp.yandex.ru
    port: 465
    username: nosoff.4ndr@yandex.ru #bigdata.andrew@gmail.com
    password: xspuhikmeympubnl #A1b2c3D4