server:
  port: 8081

spring:
  sql:
    init:
      mode: always
      encoding: UTF-8

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
    defer-datasource-initialization: true
  mail:
    host: smtp.yandex.ru
    username: Passw0rd #bigdata.andrew@gmail.com
    password: uaionrmlxlutbylv #A1b2c3D4
    properties:
      mail:
        transport.protocol: smtp
        smtp:
          port: 465
          auth: false
          starttls:
            enable: true
            required: true
  task:
    scheduling:
      pool:
        size: 10