server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bigdata
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
  mail:
    host: smtp.yandex.ru
    username: Passw0rd #bigdata.andrew@gmail.com
    password: uaionrmlxlutbylv #A1b2c3D4
    properties:
      mail:
        transport.protocol: smtp
        smtp:
          port: 465
          auth: false
          starttls:
            enable: true
            required: true