alter table if exists auto_loan_auto_loan_cache drop constraint if exists FK11h8yiebvrmxuruyfl2xg82bx;
alter table if exists auto_loan_auto_loan_cache drop constraint if exists FKc840s9wxp3aal5o4fbl5r6911;
alter table if exists auto_loan_cache drop constraint if exists FK475el62dkc96c27klf8gymt41;
alter table if exists consumer_cache drop constraint if exists FKkxpjcu9nmacenxthbb9sm6503;
alter table if exists consumer_consumer_cache drop constraint if exists FKg6oxpftucbrafc4aeipbpg9tq;
alter table if exists consumer_consumer_cache drop constraint if exists FKkk40uvwvhov80maiqop04emgh;
alter table if exists current_debt_load drop constraint if exists FKfxfww9hsv3rvptrgtns45q1th;
alter table if exists loan_application drop constraint if exists FKd2f1sth3m3iou0804n8o79pp3;
alter table if exists loan_application drop constraint if exists FKejcvlj6ab0mukole0gskdttrn;
alter table if exists loan_application drop constraint if exists FKn5gbwiha9qyf6koo4c6c8fgfs;
alter table if exists mortgage_cache drop constraint if exists FK6tlmmpklr1j45h13y1dicyt3k;
alter table if exists mortgage_mortgage_cache drop constraint if exists FKnwhc7w8yktqq25a7hgw88ypdc;
alter table if exists mortgage_mortgage_cache drop constraint if exists FKciq0bu5xle98imxa30jxli4uv;
alter table if exists widget_entity drop constraint if exists FKe7vg24ubctffdk8tso3ggyoqc;
alter table if exists work_experience drop constraint if exists FKkuvu34c8i4y5p4x7vjc07w6mk;
drop table if exists auto_loan cascade;
drop table if exists auto_loan_auto_loan_cache cascade;
drop table if exists auto_loan_cache cascade;
drop table if exists consumer cascade;
drop table if exists consumer_cache cascade;
drop table if exists consumer_consumer_cache cascade;
drop table if exists current_debt_load cascade;
drop table if exists loan_application cascade;
drop table if exists mortgage cascade;
drop table if exists mortgage_cache cascade;
drop table if exists mortgage_mortgage_cache cascade;
drop table if exists themes_widget;
drop table if exists users cascade;
drop table if exists widget_entity cascade;
drop table if exists work_experience cascade;
drop sequence if exists auto_loan_cache_seq;
drop sequence if exists consumer_cache_seq;
drop sequence if exists mortgage_cache_seq;
create sequence auto_loan_cache_seq start with 1 increment by 50;
create sequence consumer_cache_seq start with 1 increment by 50;
create sequence mortgage_cache_seq start with 1 increment by 50;
create table auto_loan (id serial not null, is_active boolean, comment VARCHAR(2048), finish_date timestamp(6), max_amount float4, max_term float4, min_amount float4, min_rate float4, min_term float4, name varchar(255), is_perpetual boolean, start_date timestamp(6), url varchar(255), car_mileage varchar(255), primary key (id));
create table auto_loan_auto_loan_cache (auto_loan_entity_id serial not null, auto_loan_cache_id integer not null);
create table auto_loan_cache (id integer not null, lending_type varchar(255), product bytea, auto_loan_id serial, primary key (id));
create table consumer (id serial not null, is_active boolean, comment VARCHAR(2048), finish_date timestamp(6), max_amount float4, max_term float4, min_amount float4, min_rate float4, min_term float4, name varchar(255), is_perpetual boolean, start_date timestamp(6), url varchar(255), discount varchar(255), primary key (id));
create table consumer_cache (id integer not null, lending_type varchar(255), product bytea, consumer_id serial, primary key (id));
create table consumer_consumer_cache (consumer_entity_id serial not null, consumer_cache_id integer not null);
create table current_debt_load (id serial not null, amount_of_monthly_loan_payments float4, count_active_loans varchar(255), monthly_income float4, loan_application integer, primary key (id));
create table loan_application (id serial not null, date_and_time_of_application timestamp(6), consent_to_the_processing_of_personal_data boolean, consent_to_a_request_to_the_credit_bureau boolean, consent_to_advertising boolean, amount_of_credit float4, having_down_payment boolean, final_scoring float4, far_east_inhabitant boolean, it_specialist boolean, military boolean, resident_of_the_new_subjects boolean, is_psb_client boolean, state_employee boolean, lending_type varchar(255), desired_loan_term float4, availability_of_open_loans boolean, opportunity_to_offer_a_loan_product boolean, status varchar(255), current_debt_load_id integer, user_id serial, work_experience_id integer, primary key (id));
create table mortgage (id serial not null, is_active boolean, comment VARCHAR(2048), finish_date timestamp(6), max_amount float4, max_term float4, min_amount float4, min_rate float4, min_term float4, name varchar(255), is_perpetual boolean, start_date timestamp(6), url varchar(255), addition_to_interest varchar(255), down_payment varchar(255), primary key (id));
create table mortgage_cache (id integer not null, lending_type varchar(255), product bytea, mortgage_id serial, primary key (id));
create table mortgage_mortgage_cache (mortgage_entity_id serial not null, mortgage_cache_id integer not null);
create table themes_widget (id serial not null, color varchar(255), font_family varchar(255), name varchar(255), primary key (id));
create table users (id serial not null, date_of_birth date, email varchar(255), firstname varchar(255), lastname varchar(255), login varchar(255), obtained_from_a_third_party_service boolean, password varchar(255), phone varchar(255), role varchar(255), surname varchar(255), primary key (id));
create table widget_entity (id serial not null, interest_rate float(53), theme_id integer, primary key (id));
create table work_experience (id serial not null, name varchar(255), loan_application integer, primary key (id));
alter table if exists auto_loan_auto_loan_cache add constraint UK_6ld4eqprmb0aiw9vbya4rtxh8 unique (auto_loan_cache_id);
alter table if exists consumer_consumer_cache add constraint UK_bd0m2m3kl99nf94n231f43dla unique (consumer_cache_id);
alter table if exists mortgage_mortgage_cache add constraint UK_8tria59y6r0olc1tdipmi76y4 unique (mortgage_cache_id);
alter table if exists auto_loan_auto_loan_cache add constraint FK11h8yiebvrmxuruyfl2xg82bx foreign key (auto_loan_cache_id) references auto_loan_cache;
alter table if exists auto_loan_auto_loan_cache add constraint FKc840s9wxp3aal5o4fbl5r6911 foreign key (auto_loan_entity_id) references auto_loan;
alter table if exists auto_loan_cache add constraint FK475el62dkc96c27klf8gymt41 foreign key (auto_loan_id) references auto_loan;
alter table if exists consumer_cache add constraint FKkxpjcu9nmacenxthbb9sm6503 foreign key (consumer_id) references consumer;
alter table if exists consumer_consumer_cache add constraint FKg6oxpftucbrafc4aeipbpg9tq foreign key (consumer_cache_id) references consumer_cache;
alter table if exists consumer_consumer_cache add constraint FKkk40uvwvhov80maiqop04emgh foreign key (consumer_entity_id) references consumer;
alter table if exists current_debt_load add constraint FKfxfww9hsv3rvptrgtns45q1th foreign key (loan_application) references loan_application;
alter table if exists loan_application add constraint FKd2f1sth3m3iou0804n8o79pp3 foreign key (current_debt_load_id) references current_debt_load;
alter table if exists loan_application add constraint FKejcvlj6ab0mukole0gskdttrn foreign key (user_id) references users;
alter table if exists loan_application add constraint FKn5gbwiha9qyf6koo4c6c8fgfs foreign key (work_experience_id) references work_experience;
alter table if exists mortgage_cache add constraint FK6tlmmpklr1j45h13y1dicyt3k foreign key (mortgage_id) references mortgage;
alter table if exists mortgage_mortgage_cache add constraint FKnwhc7w8yktqq25a7hgw88ypdc foreign key (mortgage_cache_id) references mortgage_cache;
alter table if exists mortgage_mortgage_cache add constraint FKciq0bu5xle98imxa30jxli4uv foreign key (mortgage_entity_id) references mortgage;
alter table if exists widget_entity add constraint FKe7vg24ubctffdk8tso3ggyoqc foreign key (theme_id) references themes_widget;
alter table if exists work_experience add constraint FKkuvu34c8i4y5p4x7vjc07w6mk foreign key (loan_application) references loan_application;