services:

  document-flow:
    build: ./
    image: back-1.0-SNAPSHOT
    container_name: back-1.0-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - document-flow-db

  document-flow-db:
    image: postgres:14-alpine
    container_name: document-flow-db
    ports:
      - "6541:5432"