# base image
#FROM node:16.0-alpine

# set working directory
#WORKDIR ./front

# add `/app/node_modules/.bin` to $PATH
#ENV PATH ./front/node_modules/.bin:$PATH

# install and cache app dependencies
#COPY package.json /src/package.json
#RUN npm install
#RUN npm install @vue/cli@3.7.0 -g

#EXPOSE 4200
# start app
#CMD ["npm", "run", "serve"]
